from setuptools import setup, find_packages

setup(
    name='agent_collab',
    version='0.1.0',
    packages=find_packages(),
    description='Reusable package with future city library stubs',
    author='Generated by AI',
    install_requires=[],
)
